import express from "express";
import { verifyToken } from "../middleware/verifyToken.js";
import { createPayment, getPaymentStatus, payfastItn, retryPayment, getPaymentConfig } from "../controllers/paymentController.js";
const router = express.Router();
router.get("/config", getPaymentConfig);
router.post("/payfast/itn", payfastItn);
router.post("/create", verifyToken, createPayment);
router.post("/payfast/create", verifyToken, createPayment);
router.post("/:orderNumber/retry", verifyToken, retryPayment);
router.get("/:orderNumber/status", verifyToken, getPaymentStatus);
export default router;
